[package]
name = "nexus-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
nexus-rt = { git = "https://github.com/nexus-xyz/nexus-zkvm.git" }
sqlparser = { version = "0.44", default-features = false }

[[bin]]
name = "parse_sql"
path = "src/parse_sql.rs"
